version: '3.8'

services:
  postgres:
    image: postgres
    environment:
        POSTGRES_USER: Admin
        POSTGRES_PASSWORD: Pass
        POSTGRES_DB: MeetingRoom
    ports:
        - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 6060:80
    depends_on:
      - postgres