version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: postgres://Admin:Pass@postgres:5432/MeetingRoom
  app:
    image: node:20
    command: npm run start
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    working_dir: /app/frontend
    environment:
      REACT_APP_API_URL: http://localhost:3000
    depends_on:
      - api
  postgres:
    image: postgres
    environment:
        POSTGRES_USER: Admin
        POSTGRES_PASSWORD: Pass
        POSTGRES_DB: MeetingRoom
    ports:
        - "5432:5432"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: example
    ports:
      - 6060:80
    depends_on:
      - postgres